config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'signin', to: 'users#new', as: 'signin'
  post 'create', to: 'users#create', as: 'user_create'
  get 'users/:id/show', to: 'users#show', as: 'show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :details, class_name: "PostDetail"
  belongs_to :toukousya, class_name: "User", foreign_key: "user_id"
end

app/models/post_detail.rb
class PostDetail < ApplicationRecord
  belongs_to :post, class_name: "Post", foreign_key: "post_id"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :toukou, class_name: "Post"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to show_path(@user)
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :passowrd_cofirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<% @posts.each do |post| %>
<%= post.title %> | <%= post.toukousya.name %><br />
<% post.details.each do |detail| %>
<%= detail.content %>
<% end %>
<% end %>

app/views/users/new.html.erb
<h1>会員登録</h1>
<%= form_for( @user , url: user_create_path) do |f| %>
なまえ：<%= f.text_field :name %><br />
めーる：<%= f.text_field :email %><br />
パスワード：<%= f.text_field :password %><br />
パスワード再確認：<%= f.text_field :password_confirmation %><br />
<%= f.submit "登録" %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>